export const HOME_MOCK = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/8sMmAmN2x7mBiNKEX2o0aOTozEB.jpg',
      genre_ids: [28, 12, 878],
      id: 505642,
      original_language: 'en',
      original_title: 'Black Panther: Wakanda Forever',
      overview:
        'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
      popularity: 4594.775,
      poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
      release_date: '2022-11-09',
      title: 'Black Panther: Wakanda Forever',
      video: false,
      vote_average: 7.6,
      vote_count: 465,
    },
    {
      adult: false,
      backdrop_path: '/u9Io1hVnxb2b3T0z99aOK8sq0SN.jpg',
      genre_ids: [9648, 12, 80],
      id: 829280,
      original_language: 'en',
      original_title: 'Enola Holmes 2',
      overview:
        'Now a detective-for-hire like her infamous brother, Enola Holmes takes on her first official case to find a missing girl, as the sparks of a dangerous conspiracy ignite a mystery that requires the help of friends — and Sherlock himself — to unravel.',
      popularity: 4081.058,
      poster_path: '/tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg',
      release_date: '2022-11-04',
      title: 'Enola Holmes 2',
      video: false,
      vote_average: 7.7,
      vote_count: 761,
    },
    {
      adult: false,
      backdrop_path: '/nnUQqlVZeEGuCRx8SaoCU4XVHJN.jpg',
      genre_ids: [14, 12, 10751],
      id: 532639,
      original_language: 'en',
      original_title: 'Pinocchio',
      overview:
        'A wooden puppet embarks on a thrilling adventure to become a real boy.',
      popularity: 1266.466,
      poster_path: '/g8sclIV4gj1TZqUpnL82hKOTK3B.jpg',
      release_date: '2022-09-07',
      title: 'Pinocchio',
      video: false,
      vote_average: 6.7,
      vote_count: 1057,
    },
    {
      adult: false,
      backdrop_path: '/5hoS3nEkGGXUfmnu39yw1k52JX5.jpg',
      genre_ids: [28, 12, 14],
      id: 960704,
      original_language: 'ja',
      original_title: '鋼の錬金術師 完結編 最後の錬成',
      overview:
        'The Elric brothers’ long and winding journey comes to a close in this epic finale, where they must face off against an unworldly, nationwide threat.',
      popularity: 1339.485,
      poster_path: '/AeyiuQUUs78bPkz18FY3AzNFF8b.jpg',
      release_date: '2022-06-24',
      title: 'Fullmetal Alchemist: The Final Alchemy',
      video: false,
      vote_average: 6.3,
      vote_count: 118,
    },
    {
      adult: false,
      backdrop_path: '/3PieOs1t6dPHWlgvX3XoqTIQLqN.jpg',
      genre_ids: [12, 28, 878],
      id: 507086,
      original_language: 'en',
      original_title: 'Jurassic World Dominion',
      overview:
        'Four years after the destruction of Isla Nublar, Biosyn operatives attempt to track down Maisie Lockwood, while Dr Ellie Sattler investigates a genetically engineered swarm of giant insects.',
      popularity: 1267.666,
      poster_path: '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg',
      release_date: '2022-06-01',
      title: 'Jurassic World Dominion',
      video: false,
      vote_average: 7,
      vote_count: 3827,
    },
    {
      adult: false,
      backdrop_path: '/Ach0puWzxuO2imh1yWEUK7CGsx.jpg',
      genre_ids: [16, 12, 28, 14],
      id: 900667,
      original_language: 'ja',
      original_title: 'ONE PIECE FILM RED',
      overview:
        'Uta — the most beloved singer in the world. Her voice, which she sings with while concealing her true identity, has been described as “otherworldly.” She will appear in public for the first time at a live concert. As the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound.',
      popularity: 1007.794,
      poster_path: '/m80kPdrmmtEh9wlLroCp0bwUGH0.jpg',
      release_date: '2022-08-06',
      title: 'One Piece Film Red',
      video: false,
      vote_average: 7.3,
      vote_count: 171,
    },
    {
      adult: false,
      backdrop_path: '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
      genre_ids: [28, 12, 878],
      id: 634649,
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      overview:
        'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      popularity: 1128.705,
      poster_path: '/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg',
      release_date: '2021-12-15',
      title: 'Spider-Man: No Way Home',
      video: false,
      vote_average: 8,
      vote_count: 15804,
    },
    {
      adult: false,
      backdrop_path: '/2k9tBql5GYH328Krj66tDT9LtFZ.jpg',
      genre_ids: [53, 12, 27],
      id: 760741,
      original_language: 'en',
      original_title: 'Beast',
      overview:
        'A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.',
      popularity: 1058.192,
      poster_path: '/xIGr7UHsKf0URWmyyd5qFMAq4d8.jpg',
      release_date: '2022-08-11',
      title: 'Beast',
      video: false,
      vote_average: 7,
      vote_count: 791,
    },
    {
      adult: false,
      backdrop_path: '/yEQqrW61rwNuVRHTjgHOAU4dXNE.jpg',
      genre_ids: [28, 12, 10751, 35],
      id: 675353,
      original_language: 'en',
      original_title: 'Sonic the Hedgehog 2',
      overview:
        'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
      popularity: 918.615,
      poster_path: '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
      release_date: '2022-03-30',
      title: 'Sonic the Hedgehog 2',
      video: false,
      vote_average: 7.6,
      vote_count: 3332,
    },
    {
      adult: false,
      backdrop_path: '/6ELJEzQJ3Y45HczvreC3dg0GV5R.jpg',
      genre_ids: [28, 12, 878],
      id: 284054,
      original_language: 'en',
      original_title: 'Black Panther',
      overview:
        "King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
      popularity: 1006.821,
      poster_path: '/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
      release_date: '2018-02-13',
      title: 'Black Panther',
      video: false,
      vote_average: 7.4,
      vote_count: 19759,
    },
    {
      adult: false,
      backdrop_path: '/aIkG2V4UXrfkxMdJZmq30xO0QQr.jpg',
      genre_ids: [878, 12, 28],
      id: 791155,
      original_language: 'en',
      original_title: 'Secret Headquarters',
      overview:
        'While hanging out after school, Charlie and his friends discover the headquarters of the world’s most powerful superhero hidden beneath his home. When villains attack, they must team up to defend the headquarters and save the world.',
      popularity: 901.682,
      poster_path: '/8PsHogUfvjWPGdWAI5uslDhHDx7.jpg',
      release_date: '2022-08-12',
      title: 'Secret Headquarters',
      video: false,
      vote_average: 6.9,
      vote_count: 154,
    },
    {
      adult: false,
      backdrop_path: '/7ABsaBkO1jA2psC8Hy4IDhkID4h.jpg',
      genre_ids: [28, 12, 14, 878],
      id: 19995,
      original_language: 'en',
      original_title: 'Avatar',
      overview:
        'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
      popularity: 936.245,
      poster_path: '/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg',
      release_date: '2009-12-15',
      title: 'Avatar',
      video: false,
      vote_average: 7.5,
      vote_count: 26528,
    },
    {
      adult: false,
      backdrop_path: '/gUNRlH66yNDH3NQblYMIwgZXJ2u.jpg',
      genre_ids: [14, 28, 12],
      id: 453395,
      original_language: 'en',
      original_title: 'Doctor Strange in the Multiverse of Madness',
      overview:
        'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
      popularity: 857.596,
      poster_path: '/fwBl3J2aEXru6mrr9Xg8O99Iz2K.jpg',
      release_date: '2022-05-04',
      title: 'Doctor Strange in the Multiverse of Madness',
      video: false,
      vote_average: 7.4,
      vote_count: 6299,
    },
    {
      adult: false,
      backdrop_path: '/198vrF8k7mfQ4FjDJsBmdQcaiyq.jpg',
      genre_ids: [878, 28, 12],
      id: 76600,
      original_language: 'en',
      original_title: 'Avatar: The Way of Water',
      overview:
        'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
      popularity: 902.434,
      poster_path: '/94xxm5701CzOdJdUEdIuwqZaowx.jpg',
      release_date: '2022-12-14',
      title: 'Avatar: The Way of Water',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/a6OX0pzbcPHstcNPK3FSJGq8Sxp.jpg',
      genre_ids: [16, 14, 12],
      id: 955644,
      original_language: 'en',
      original_title: 'Mia and Me: The Hero of Centopia',
      overview:
        'Mia discovers her magic stone is part of an ancient prophecy and embarks on a thrilling journey to the farthest islands of Centopia to face a great evil, and shape her own destiny.',
      popularity: 822.236,
      poster_path: '/a3ZpDsvNCQUOD7ApAs9y3mFwVU4.jpg',
      release_date: '2022-05-26',
      title: 'Mia and Me: The Hero of Centopia',
      video: false,
      vote_average: 7.3,
      vote_count: 34,
    },
    {
      adult: false,
      backdrop_path: '/3p3amyz5nXK9AW4VARqkPaMAG5J.jpg',
      genre_ids: [16, 12, 35, 14],
      id: 585511,
      original_language: 'en',
      original_title: 'Luck',
      overview:
        'Suddenly finding herself in the never-before-seen Land of Luck, the unluckiest person in the world must unite with the magical creatures there to turn her luck around.',
      popularity: 727.412,
      poster_path: '/1HOYvwGFioUFL58UVvDRG6beEDm.jpg',
      release_date: '2022-08-05',
      title: 'Luck',
      video: false,
      vote_average: 7.9,
      vote_count: 893,
    },
    {
      adult: false,
      backdrop_path: '/qjGrUmKW78MCFG8PTLDBp67S27p.jpg',
      genre_ids: [16, 28, 12, 14],
      id: 635302,
      original_language: 'ja',
      original_title: '劇場版「鬼滅の刃」無限列車編',
      overview:
        "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
      popularity: 697.519,
      poster_path: '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg',
      release_date: '2020-10-16',
      title: 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
      video: false,
      vote_average: 8.3,
      vote_count: 2779,
    },
    {
      adult: false,
      backdrop_path: '/apBUC70udhxoLzXo7DqclQ6gcXo.jpg',
      genre_ids: [16, 35, 14, 12],
      id: 511817,
      original_language: 'en',
      original_title: 'Wendell & Wild',
      overview:
        'Two demon brothers enlist the aid of Kat Elliot — a tough teen with a load of guilt — to summon them to the Land of the Living. But what Kat demands in return leads to a brilliantly bizarre and comedic adventure like no other.',
      popularity: 593.383,
      poster_path: '/5dsX6UAHqkQz1kiV8bs8SvjyVNa.jpg',
      release_date: '2022-10-21',
      title: 'Wendell & Wild',
      video: false,
      vote_average: 6.8,
      vote_count: 110,
    },
    {
      adult: false,
      backdrop_path: '/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
      genre_ids: [10751, 16, 14, 10402, 35, 12],
      id: 354912,
      original_language: 'en',
      original_title: 'Coco',
      overview:
        "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel's family history.",
      popularity: 577.676,
      poster_path: '/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
      release_date: '2017-10-27',
      title: 'Coco',
      video: false,
      vote_average: 8.2,
      vote_count: 16481,
    },
    {
      adult: false,
      backdrop_path: '/mjV9gpXO2R2SOYI4ChJZiu6F1OE.jpg',
      genre_ids: [28, 12, 53],
      id: 759507,
      original_language: 'en',
      original_title: 'Blackout',
      overview:
        'A man wakes in a hospital with no memory, and quickly finds himself on the run in a locked down hospital with the Cartel on his tail.',
      popularity: 582.546,
      poster_path: '/xDgnmbdWS59NtTPdzujdZGuPUPZ.jpg',
      release_date: '2022-10-12',
      title: 'Blackout',
      video: false,
      vote_average: 5.5,
      vote_count: 83,
    },
  ],
  total_pages: 932,
  total_results: 18631,
};
