export const DETAILS_MOCK = {
  adult: false,
  backdrop_path: '/Ach0puWzxuO2imh1yWEUK7CGsx.jpg',
  belongs_to_collection: {
    id: 23456,
    name: 'One Piece Collection',
    poster_path: '/zwXYjITRboH7nKGQmPXmCMRUHol.jpg',
    backdrop_path: '/3RqSKjokWlXyTBUt3tcR9CrOG57.jpg',
  },
  budget: 0,
  genres: [
    { id: 16, name: 'Animation' },
    { id: 12, name: 'Adventure' },
    { id: 28, name: 'Action' },
    { id: 14, name: 'Fantasy' },
  ],
  homepage: 'https://www.onepiece-filmred.com',
  id: 900667,
  imdb_id: 'tt16183464',
  original_language: 'ja',
  original_title: 'ONE PIECE FILM RED',
  overview:
    'Uta — the most beloved singer in the world. Her voice, which she sings with while concealing her true identity, has been described as “otherworldly.” She will appear in public for the first time at a live concert. As the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound.',
  popularity: 1007.794,
  poster_path: '/m80kPdrmmtEh9wlLroCp0bwUGH0.jpg',
  production_companies: [
    {
      id: 1778,
      logo_path: '/69xm6sF3JxugGVjfZfm1YY6d7EE.png',
      name: 'dentsu',
      origin_country: 'JP',
    },
    {
      id: 2918,
      logo_path: '/gyEWUBWwqrm3H5T2hkERD9LxpOq.png',
      name: 'Shueisha',
      origin_country: 'JP',
    },
    {
      id: 3341,
      logo_path: '/dTG5dXE1kU2mpmL9BNnraffckLU.png',
      name: 'Fuji Television Network',
      origin_country: 'JP',
    },
    {
      id: 5542,
      logo_path: '/ayE4LIqoAWotavo7xdvYngwqGML.png',
      name: 'Toei Animation',
      origin_country: 'JP',
    },
    {
      id: 5822,
      logo_path: '/qyTbRgCyU9NLKvKaiQVbadtr7RY.png',
      name: 'Toei Company',
      origin_country: 'JP',
    },
    {
      id: 12502,
      logo_path: '/aDcFy26DtVbyZIFOZNTLsooWH5X.png',
      name: 'Bandai Namco Entertainment',
      origin_country: 'JP',
    },
    {
      id: 155586,
      logo_path: '/rogLuRSNdqLI9r29ZCzD0i0kfJW.png',
      name: 'Bandai',
      origin_country: 'JP',
    },
    {
      id: 173235, logo_path: null, name: 'ADK Emotions', origin_country: 'JP',
    },
  ],
  production_countries: [{ iso_3166_1: 'JP', name: 'Japan' }],
  release_date: '2022-08-06',
  revenue: 150797338,
  runtime: 115,
  spoken_languages: [
    { english_name: 'Japanese', iso_639_1: 'ja', name: '日本語' },
  ],
  status: 'Released',
  tagline: 'An almighty voice. With fiery red locks.',
  title: 'One Piece Film Red',
  video: false,
  vote_average: 7.358,
  vote_count: 172,
};
